// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<String> registerMessageStream() =>
    RustLib.instance.api.crateApiChatApiRegisterMessageStream();

Future<RustStreamSink<String>?> getMessageSink() =>
    RustLib.instance.api.crateApiChatApiGetMessageSink();

Future<String> sendDm({
  required String targetPeerId,
  required String targetPubKey,
  required String content,
}) => RustLib.instance.api.crateApiChatApiSendDm(
  targetPeerId: targetPeerId,
  targetPubKey: targetPubKey,
  content: content,
);
