// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/message.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<IdentityInfo> generateIdentity() =>
    RustLib.instance.api.crateApiCryptoApiGenerateIdentity();

Future<String> setActiveIdentity({required List<int> seed}) =>
    RustLib.instance.api.crateApiCryptoApiSetActiveIdentity(seed: seed);

Future<void> clearActiveIdentity() =>
    RustLib.instance.api.crateApiCryptoApiClearActiveIdentity();

Future<DMPayload> encryptDmMessage({
  required String plaintext,
  required String recipientPubBase64,
}) => RustLib.instance.api.crateApiCryptoApiEncryptDmMessage(
  plaintext: plaintext,
  recipientPubBase64: recipientPubBase64,
);

Future<String> decryptDmMessage({required DMPayload payload}) =>
    RustLib.instance.api.crateApiCryptoApiDecryptDmMessage(payload: payload);

class IdentityInfo {
  final Uint8List seed;
  final String peerId;
  final String signingPubkey;
  final String boxPubkey;

  const IdentityInfo({
    required this.seed,
    required this.peerId,
    required this.signingPubkey,
    required this.boxPubkey,
  });

  @override
  int get hashCode =>
      seed.hashCode ^
      peerId.hashCode ^
      signingPubkey.hashCode ^
      boxPubkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          seed == other.seed &&
          peerId == other.peerId &&
          signingPubkey == other.signingPubkey &&
          boxPubkey == other.boxPubkey;
}
