// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<String> registerPeerEventStream() =>
    RustLib.instance.api.crateApiNodeApiRegisterPeerEventStream();

Future<RustStreamSink<String>?> getPeerEventSink() =>
    RustLib.instance.api.crateApiNodeApiGetPeerEventSink();

Future<String> startNode() => RustLib.instance.api.crateApiNodeApiStartNode();

Future<void> stopNode() => RustLib.instance.api.crateApiNodeApiStopNode();

Future<bool> isNodeRunning() =>
    RustLib.instance.api.crateApiNodeApiIsNodeRunning();

Future<String?> getPeerId() => RustLib.instance.api.crateApiNodeApiGetPeerId();

Future<void> dialPeer({required String multiaddr}) =>
    RustLib.instance.api.crateApiNodeApiDialPeer(multiaddr: multiaddr);

Future<BigInt> getPeerCount() =>
    RustLib.instance.api.crateApiNodeApiGetPeerCount();

Future<bool> subscribeToTopic({required String topic}) =>
    RustLib.instance.api.crateApiNodeApiSubscribeToTopic(topic: topic);

Future<bool> unsubscribeFromTopic({required String topic}) =>
    RustLib.instance.api.crateApiNodeApiUnsubscribeFromTopic(topic: topic);

Future<void> publishMessage({required String topic, required List<int> data}) =>
    RustLib.instance.api.crateApiNodeApiPublishMessage(
      topic: topic,
      data: data,
    );

Future<void> publishPresence() =>
    RustLib.instance.api.crateApiNodeApiPublishPresence();
