// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DMPayload {
  final String nonce;
  final String ciphertext;
  final String senderPubKey;

  const DMPayload({
    required this.nonce,
    required this.ciphertext,
    required this.senderPubKey,
  });

  @override
  int get hashCode =>
      nonce.hashCode ^ ciphertext.hashCode ^ senderPubKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DMPayload &&
          runtimeType == other.runtimeType &&
          nonce == other.nonce &&
          ciphertext == other.ciphertext &&
          senderPubKey == other.senderPubKey;
}
